config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :sales
  resources :drivers
  resources :car_bodies
  resources :car_heads
  resources :orders
  resources :admins

  get '' => 'main#index', as: :root

  # session
  get 'login' => 'session#index', as: :login
  post 'login' => 'session#login', as: :do_login
  post 'logout' => 'session#logout', as: :logout

  get 'profile' => 'admins#profile', as: :profile

  # counts
  get 'counts' => 'main#counts'
  get 'products_count' => 'main#products_count'
  get 'viewers_count' => 'main#viewers_count'
  get 'total_count' => 'main#total_count'
  get 'statistic_order_map' => 'main#statistic_order_map'
  post 'upload_token' => 'image_uploader#get_upload_token'
  post 'upload_video_token' => 'image_uploader#upload_video_token'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @schedules = Schedule.limit(3)
    @orders = Order.onprogress.limit(10)
    @car_heads = CarHead.limit(100)
    @car_bodies = CarBody.limit(100)
    @drivers = Driver.all.includes(:cur_orders)
  end

  def counts
    info = Rails.cache.fetch(cache_key.to_s, expires_in: 5.minutes) do
      set_counts
    end

    render json: info.to_json
  end

  def products_count
    info = Rails.cache.fetch(cache_key.to_s, expires_in: 10.minutes) do
      cates = Category.limit(5)
      counts = {}
      cates.each do |c|
        counts[c.name] = c.products.count
      end
      counts['其它'] = (counts['其它'] || 0) +
                     Product.where.not(category_id: cates.map(&:id)).count +
                     Product.where(category_id: nil).count
      counts
    end

    render json: info.to_json
  end

  def statistic_order_map
    render json: Order.statistics_map(10.days.ago.midnight, Time.now)
  end

  def total_count
    info = Rails.cache.fetch(cache_key.to_s, expires_in: 10.minutes) do
      set_m_p_v_info
    end

    render json: info.to_json
  end

  def viewers_count
    info = Rails.cache.fetch(cache_key.to_s, expires_in: 10.minutes) do
      set_v_info
    end

    # 每新的一天清除旧缓存
    interval = Time.now - Time.now.midnight
    if (interval < 10.minutes) && (interval < Time.now - info[:time])
      Rails.cache.delete cache_key
      info = set_v_info
      info_0 = set_v_info_0
    else
      info_0 = Rails.cache.fetch("#{cache_key}_0", expires_in: 1.minutes) do
        set_v_info_0
      end
    end

    render json: info.merge(info_0).to_json
  end

  private

  def set_counts
    {
      o_count: Order.unscope(:where).count, # 订单总数
      c_count: CarHead.unscope(:where).count, # 车辆总数
      s_count: Schedule.unscope(:where).count, # 计划总数
      total_money: Order.success.sum(:price), # 总成交金额
      t_o_count: Order.where(created_at: Time.now.midnight..Time.now).count, # 今日订单
      t_s_count: Schedule.where("begin_time <= ? and end_time >= ?", 1.days.after.midnight, Time.now.midnight).count, # 今日计划
      today_money: Order.where(created_at: Time.now.midnight..Time.now).success.sum(:price) # 今日成交额
    }
  end

  def set_v_info
    {
      # 营收
      m_1_count: Order.success.where(created_at: 1.day.ago.midnight..Time.now.midnight).sum(:price), # 昨天收益
      m_2_count: Order.success.where(created_at: 2.days.ago.midnight..1.day.ago.midnight).sum(:price), # 前天收益
      m_3_count: Order.success.where(created_at: 3.days.ago.midnight..2.days.ago.midnight).sum(:price), # 大前天收益
      m_4_count: Order.success.where(created_at: 4.days.ago.midnight..3.days.ago.midnight).sum(:price), # 前四天收益
      m_5_count: Order.success.where(created_at: 5.days.ago.midnight..4.days.ago.midnight).sum(:price), # 前五天收益
      m_6_count: Order.success.where(created_at: 6.days.ago.midnight..5.days.ago.midnight).sum(:price), # 前六天收益
      m_7_count: Order.success.where(created_at: 7.days.ago.midnight..6.days.ago.midnight).sum(:price), # 前七天收益

      c_1_count: Order.where(created_at: 1.day.ago.midnight..Time.now.midnight).sum(:total_fee), # 昨天运营成本
      c_2_count: Order.where(created_at: 2.days.ago.midnight..1.day.ago.midnight).sum(:total_fee), # 前天运营成本
      c_3_count: Order.where(created_at: 3.days.ago.midnight..2.days.ago.midnight).sum(:total_fee), # 大前天运营成本
      c_4_count: Order.where(created_at: 4.days.ago.midnight..3.days.ago.midnight).sum(:total_fee), # 前四天运营成本
      c_5_count: Order.where(created_at: 5.days.ago.midnight..4.days.ago.midnight).sum(:total_fee), # 前五天运营成本
      c_6_count: Order.where(created_at: 6.days.ago.midnight..5.days.ago.midnight).sum(:total_fee), # 前六天运营成本
      c_7_count: Order.where(created_at: 7.days.ago.midnight..6.days.ago.midnight).sum(:total_fee), # 前七天运营成本

      # 订单交易量
      o_1_count: Order.where(created_at: 1.day.ago.midnight..Time.now.midnight).count, # 昨天交易量
      o_2_count: Order.where(created_at: 2.days.ago.midnight..1.day.ago.midnight).count, # 前天交易量
      o_3_count: Order.where(created_at: 3.days.ago.midnight..2.days.ago.midnight).count, # 大前天交易量
      o_4_count: Order.where(created_at: 4.days.ago.midnight..3.days.ago.midnight).count, # 前四天交易量
      o_5_count: Order.where(created_at: 5.days.ago.midnight..4.days.ago.midnight).count, # 前五天交易量
      o_6_count: Order.where(created_at: 6.days.ago.midnight..5.days.ago.midnight).count, # 前六天交易量
      o_7_count: Order.where(created_at: 7.days.ago.midnight..6.days.ago.midnight).count, # 前七天交易量

      # 记录缓存时间
      time: Time.now
    }
  end

  def set_v_info_0
    {
      c_1_count: Order.where(created_at: Time.now.midnight..Time.now).sum(:total_fee), # 昨天交易量
      m_0_count: Order.success.where(created_at: Time.now.midnight..Time.now).sum(:price), # 今日收入
      o_0_count: Order.where(created_at: Time.now.midnight..Time.now).count # 商品今天购买量
    }
  end

  def set_m_p_v_info
    {
      p_t_v_count: Order.where(updated_at: Time.now.midnight..Time.now).count, # 商品今天访客量
      p_v_count: Order.count, # 商品总访客量
      total_viewers_count: LoginRecord.count # 本站总访客量
    }
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<!-- page heading start-->
<div class="page-heading">
  <div class="row">
    <div class="col-md-2">
      <h3>
        众卡之家后台管理
      </h3>
      <ul class="breadcrumb">
        <li class="active">
          系统首页
        </li>
      </ul>
    </div>
      <div class="col-md-10">
        <div class="state-info">
          <section class="panel">
            <div class="panel-body">
              <div class="summary">
                <span>今日成交额</span>
                <h3 class="red-txt" id='today-money'>-</h3>
              </div>
              <div id="money" class="chart-bar"></div>
            </div>
          </section>
          <section class="panel">
            <div class="panel-body">
              <div class="summary">
                <span>今日订单</span>
                <h3 class="red-txt" id='t-o-count'>-</h3>
              </div>
              <div id="income" class="chart-bar"></div>
            </div>
          </section>
          <section class="panel">
            <div class="panel-body">
              <div class="summary">
                <span>今日计划</span>
                <h3 class="green-txt" id='t-s-count'>-</h3>
              </div>
              <div id="expense" class="chart-bar"></div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
  <!-- page heading end-->
  <!--body wrapper start-->
  <div class="wrapper">
    <div class="row">
      <div class="col-md-6">
        <!--statistics start-->
        <div class="row state-overview">
          <div class="col-md-6 col-xs-6 col-sm-6">
            <div class="panel purple">
              <div class="symbol">
                <i class="glyphicon glyphicon-shopping-cart"></i>
              </div>
              <div class="state-value">
                <div class="value">
                  <%= link_to '-', orders_path, id: 'o-count' %>
                </div>
                <div class="title">订单总数</div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-xs-6 col-sm-6">
            <div class="panel red">
              <div class="symbol">
                <i class="fa fa-arrow-circle-o-up"></i>
              </div>
              <div class="state-value">
                <div class="value">
                  <%= link_to '-', schedules_path, id: 's-count' %>
                </div>
                <div class="title">执行计划</div>
              </div>
            </div>
          </div>
        </div>
        <!--statistics end-->
        <div class="row state-overview">
          <div class="col-md-6 col-xs-6 col-sm-6">
            <div class="panel blue">
              <div class="symbol">
                <i class="fa fa-rocket"></i>
              </div>
              <div class="state-value">
                <div class="value">
                  <%= link_to '-', car_heads_path, id: 'c-count' %>
                </div>
                <div class="title">
                  车辆总数
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-xs-6 col-sm-6">
            <div class="panel green">
              <div class="symbol">
                <i class="fa fa-money"></i>
              </div>
              <div class="state-value">
                <div class="value">
                  <%= link_to '-', orders_path, id: 'total-money' %>
                </div>
                <div class="title">
                  总成交额
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <!--more statistics box start-->
        <div class="panel">
          <div class="panel-heading">
            近期调度计划
            <small><%= link_to "更多>>", schedules_path, class: "pull-right flex" %></small>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-xs-12">
                <div id="graph-donut" class="schedule-graph">
                <table class="table table-striped table-hover table-bscheduleed" id="editable-sample">
                  <thead>
                    <tr>
                      <th>计划名称</th>
                      <th>执行者</th>
                      <th>预计执行时间</th>
                      <th>截止时间</th>
                      <th>状态</th>
                      <th>关联车头</th>
                      <th>关联挂车</th>
                    </tr>
                  </thead>
                  <tbody>
                    <!-- 此处动态生成 -->
                    <% @schedules.each do |o| %>
                      <tr>
                        <td><%= link_to o.name, schedule_path(o) %></td>
                        <td><%= o.executor %></td>
                        <td><%= o.begin_time.try :strftime, '%Y-%m-%d %H:%M:%S' %></td>
                        <td><%= o.end_time.try :strftime, '%Y-%m-%d %H:%M:%S' %></td>
                        <td><%= o.state %></td>
                        <td><%= link_to (o.car_head.try :car_number) || '', car_head_path(o.car_head_id.blank? ? 0 : o.car_head_id) %></td>
                        <td><%= link_to (o.car_body.try :body_id) || '', car_body_path(o.car_body_id.blank? ? 0 : o.car_body_id) %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              </div>
            </div>
          </div>
        </div>
        <!--more statistics box end-->
      </div>
    </div>
    <div class="row">
      <div class="col-md-7">
        <div class="panel">
          <div class="panel-body">
            <div class="row revenue-states">
              <div class="col-md-6 col-sm-6 col-xs-12">
                <h4>近期营收情况</h4>
              </div>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <ul class="revenue-nav">
                  <li class="pull-left">
                    <div id="main-chart-legend"></div>
                  </li>
                  <li class="pull-right" style="margin-right: 15px">
                    <a href="javascript: void(0)">近一周</a>
                  </li>
                  <!-- <li><a href="#">monthly</a></li> <li class="active"><a href="#">yearly</a></li> -->
                </ul>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">

                <div id="main-chart">
                  <div id="main-chart-container" class="main-chart"></div>
                </div>
                <!-- <ul class="revenue-short-info"> <li> <h1 class="red">15%</h1> <p>Server Load</p> </li> <li> <h1 class="purple">30%</h1> <p>Disk Space</p> </li> <li> <h1 class="green">84%</h1> <p>Transferred</p> </li> <li> <h1 class="blue">28%</h1>
                <p>Temperature</p> </li> </ul> -->
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-5">
        <div class="panel deep-purple-box">
          <div class="panel-body">
            <div id="car-line" style="width:100%; height:350px"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="panel">
          <div class="panel-heading">
            车头实时位置
            <small><%= link_to "更多>>", car_heads_path, class: "pull-right flex" %></small>
          </div>
          <div class="panel-body car-loc-panel">
            <table class="table table-striped table-hover table-bscheduleed" id="editable-sample">
              <thead>
                <tr>
                  <th>车头（车牌号）</th>
                  <th>当前位置</th>
                  <th>更新时间</th>
                  <th>更新</th>
                </tr>
              </thead>
              <tbody>
                <!-- 此处动态生成 -->
                <% @car_heads.each do |c| %>
                  <tr>
                    <td><%= link_to c.car_number, car_head_path(c) %></td>
                    <td class='loc'><%= c.loc %></td>
                    <td class='updated-time'><%= c.updated_at.try :strftime, '%Y-%m-%d %H:%M' %></td>
                    <td class="edit-loc" data-href="<%= car_head_path(c) %>" data-attr="car_head[loc]"><a href="javascript:void(0)" data-id="<%= c.id %>">编辑</a></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel">
          <div class="panel-heading">
            挂车实时位置
            <small><%= link_to "更多>>", car_bodies_path, class: "pull-right flex" %></small>
          </div>
          <div class="panel-body car-loc-panel">
            <table class="table table-striped table-hover table-bscheduleed" id="editable-sample">
              <thead>
                <tr>
                  <th>挂车号</th>
                  <th>当前位置</th>
                  <th>更新时间</th>
                  <th>更新</th>
                </tr>
              </thead>
              <tbody>
                <!-- 此处动态生成 -->
                <% @car_bodies.each do |c| %>
                  <tr>
                    <td><%= link_to c.body_id, car_body_path(c) %></td>
                    <td class='loc'><%= c.loc %></td>
                    <td class='updated-time'><%= c.updated_at.try :strftime, '%Y-%m-%d %H:%M' %></td>
                    <td class="edit-loc" data-href="<%= car_body_path(c) %>" data-attr="car_body[loc]"><a href="javascript:void(0)" data-id="<%= c.id %>">编辑</a></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel">
          <div class="panel-heading">
            司机实时状态
            <small><%= link_to "更多>>", drivers_path, class: "pull-right flex" %></small>
          </div>
          <div class="panel-body car-loc-panel">
            <table class="table table-striped table-hover table-bscheduleed" id="editable-sample">
              <thead>
                <tr>
                  <th>司机</th>
                  <th>当前状态</th>
                  <th>进行中的订单编号</th>
                  <th>位置轨迹</th>
                </tr>
              </thead>
              <tbody>
                <!-- 此处动态生成 -->
                <% @drivers.each do |d| %>
                  <tr>
                    <td><%= link_to d.name, driver_path(d) %></td>
                    <td><%= d.cur_orders.any? ? :运输中 : :空闲 %></td>
                    <td>
                      <% d.cur_orders.each do |o| %>
                        <%= link_to o.id.to_s + ' ', order_path(o) %>
                      <% end %>
                    </td>
                    <td><%= d.cur_orders[0] ? d.cur_orders[0].origin + '->' + d.cur_orders[0].destination : ' ' %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="panel">
          <div class="panel-heading">
            近期订单
            <small><%= link_to "更多>>", orders_path, class: "pull-right flex" %></small>
          </div>
          <div class="panel-body">
            <%= render "/orders/list" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--body wrapper end-->
</div>
<!-- main content end-->

<%= javascript_include_tag 'chart-init' %>