config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :sales
  resources :drivers
  resources :car_bodies
  resources :car_heads
  resources :orders
  resources :admins

  get '' => 'main#index', as: :root

  # session
  get 'login' => 'session#index', as: :login
  post 'login' => 'session#login', as: :do_login
  post 'logout' => 'session#logout', as: :logout

  get 'profile' => 'admins#profile', as: :profile

  # counts
  get 'counts' => 'main#counts'
  get 'products_count' => 'main#products_count'
  get 'viewers_count' => 'main#viewers_count'
  get 'total_count' => 'main#total_count'
  get 'statistic_order_map' => 'main#statistic_order_map'
  post 'upload_token' => 'image_uploader#get_upload_token'
  post 'upload_video_token' => 'image_uploader#upload_video_token'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  enum state: { 排期中: 0, 执行中: 1, 已执行: 2, 已超期: 3 }

  belongs_to :car_head,
             optional: true

  belongs_to :car_body,
             optional: true

   def self.filter(cons = {})
     _self = self
     if cons[:keywords]
       k = cons[:keywords]
       _self = _self.where('name like ? OR executor like ?', "%#{k}%", "%#{k}%")
     end
     _self = _self.unscope(where: :states).where(state: cons[:states]) if cons[:states] # 数组
     _self = _self.where('end_time <= ?', cons[:begin_before]) if cons[:begin_before]
     _self = _self.where('begin_time >= ?', cons[:begin_after]) if cons[:begin_after]
     _self
   end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :filter_cons, only: [:index, :export_xlsx]

  # GET /schedules
  # GET /schedules.json
  def index
    nonpaged_schedules = Schedule.filter(@cons).includes(:car_head, :car_body)
    @schedules = nonpaged_schedules.page(@page).per(@count)
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: '计划创建成功.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: '计划更新成功.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: '计划已删除.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:name, :begin_time, :end_time, :car_head_id, :car_body_id, :executor, :desc, :state)
    end

    def filter_cons
      @count = params[:count] || 20
      @page = params[:page] || 1
      @cons = params.slice(:keywords, :states, :begin_before, :begin_after)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_cdts.html.erb
<div class="cdts-panel">
	<header class="panel-heading c">
		<small>条件筛选</small>
		<span class="tools pull-right">
			<a class="fa fa-chevron-down" href="javascript:;" role='show-cdts'></a>
		 </span>
	</header>

	<ul class='cdts' id="cdts" style="display: none">
		<% if params[:action].to_sym == :index %>
			<li>
				<div class="options"  data-multi='true'>
					<ul class="directory-list">
						<li class='con-item' id='state' data-name="states[]">状态</li>
						<% Schedule.states.keys.each do |k| %>
							<li><a href="JavaScript: void(0)" data-value="<%= k %>" data-role='opt'><%= k %></a></li>
						<% end %>
						<li><a href="JavaScript: void(0)" data-role='opt'>不限</a></li>
					</ul>
				</div>
			</li>
		<% end %>
		<li class="inline">
				<div class="options" data-multi='true'>
				<ul class="directory-list">
					<li class='con-item' id='create_begin' data-name="begin_after">计划日期</li>
					<span class="opt-tip">开始</span>
					<li>
						<a href="JavaScript: void(0)" data-value data-role='opt'>
							<input type="text" class="date input" autocomplete="off">
						</a>
					</li>
				</ul>
			</div>
		</li>
		<li class="inline">
			<div class="options" data-multi='true'>
				<ul class="directory-list">
					<li class='con-item' id='create_end' data-name="begin_before"></li>
					<span class="opt-tip">截止</span>
					<li>
						<a href="JavaScript: void(0)" data-value data-role='opt'>
							<input type="text" class="date input" role='order-end-time' autocomplete="off">
						</a>
					</li>
				</ul>
			</div>
		</li>
	</ul>
</div>

<%= stylesheet_link_tag "cdtSelector/cdt-select" %>
<%= javascript_include_tag "cdtSelector/cdtSelect" %>
<script type="text/javascript">
	// 处理特殊的截止时间 时间+1天
	$('[role="order-end-time"]').on('change', function() {
		if ($(this).val()) {
			var d = new Date($(this).val());
			d.setDate(d.getDate() + 1)
			$(this).val([d.getFullYear(), d.getMonth() + 1, d.getDate()].join('-'));
		}
	})
</script>

app/views/schedules/_form.html.erb
<% if notice %>
  <h3><%= notice %></h3>
<% end %>
<div class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <%= form_with(model: schedule, local: true, html: { id: 'schedule-form', 'data-id' => @schedule.id, valid: false }) do |f| %>
      <div id="error">
        <% if @schedule.errors.any? %>
          <div id="error_explanation">
            <h3>存在<%= @schedule.errors.count %>个错误信息</h3>
            <ul>
              <% @schedule.errors.full_messages.each do |message| %>
                <li class="form-error"><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
      <section class='panel'>
        <div class="row">
          <div class="col-xs-12 col-sm-12">
            <div class="panel panel-split">
              <div class="panel-heading">
                计划信息
              </div>
              <div class="panel-body">
                <div class="form-group">
                  <div class="row">
                    <div class="col-sm-6">
                      <label for="schedule_name">计划名称</label>
                      <input type="text" id='schedule_name' name='schedule[name]' class="form-control" placeholder="请输入计划名称" value="<%= @schedule.name %>" >
                    </div>
                    <div class="col-sm-6">
                      <label for="schedule_executor">执行者</label>
                      <input type="text" id='schedule_executor' name='schedule[executor]' class="form-control" placeholder="请输入执行者" value="<%= @schedule.executor %>" >
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="row">
                    <div class="col-sm-6">
                      <label for="schedule_start_time">预期执行时间</label>
                      <input type="text" id='schedule_start_time' name='schedule[begin_time]' class="input datetime form-control" placeholder="请选择时间" value="<%= @schedule.begin_time %>" autocomplete="off">
                    </div>
                    <div class="col-sm-6">
                      <label for="schedule_destination">截止时间</label>
                      <input type="text" id='schedule_end_time' name='schedule[end_time]' class="input datetime form-control" placeholder="请选择时间" value="<%= @schedule.end_time %>" autocomplete="off">
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="row">
                    <div class="col-sm-6">
                      <label for="schedule_head_id">关联车头</label>
                      <input type="hidden" id='schedule_head_id' name='schedule[car_head_id]' class="form-control" placeholder="请输入车牌" value="<%= @schedule.car_head_id %>">
                      <div class="cdt-select" placeholder="输入车头号查询" data-search-url="<%= car_heads_path %>" data-default="<%= @schedule.car_head.try :car_number %>" data-key="car_number" data-keywords="schedule[car_head_id]" data-json="<%= CarHead.all.select(:id, :car_number).to_json %>"></div>
                    </div>
                    <div class="col-sm-6">
                      <label for="schedule_price">关联挂车</label>
                      <input type="hidden" id='schedule_car_body_id' name='schedule[car_body_id]' class="form-control" placeholder="请输入挂车号" value="<%= @schedule.car_body_id %>">
                      <div class="cdt-select" placeholder="输入挂车号查询" data-search-url="<%= car_bodies_path %>" data-default="<%= @schedule.car_body.try :body_id %>" data-key="body_id" data-keywords="schedule[car_body_id]" data-json="<%= CarBody.all.select(:id, :body_id).to_json %>"></div>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="row">
                    <div class="col-sm-12">
                      <label for="schedule_spec">计划状态</label>
                      <select name="schedule[state]" id="schedule_state" class="form-control">
                      <% Schedule.states.each do |pair| %>
                        <option value="<%= pair[0] %>" <%= pair[0] == @schedule.state ? :selected : '' %>><%= pair[0] %></option>
                      <% end %>
                      </select>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="row">
                    <div class="col-sm-12">
                      <label for="schedule_desc">计划描述</label>
                      <textarea id='schedule_desc' name='schedule[desc]' class="form-control" placeholder="请输入计划描述">
                        <%= @schedule.desc %>
                      </textarea>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div class="actions">
        <button id='schedule-submit' class="btn btn-primary btn-wide" href="JavaScript:void(0)">提交</button>
      </div>
    <% end %>
    </div>
  </div>
</div>

<%= stylesheet_link_tag 'cdtSelector/cdt-select-theme' %>
<%= javascript_include_tag 'cdtSelector/cdtSelect' %>
<script>
$('body').on("keydown", "input", function (event) {
  event.stopPropagation();
  var code;
  if (event) {
    event = window.event; //针对ie浏览器
  }
  code = event.keyCode;
  if (code == 13) {
    $(this).blur();
    event.preventDefault();
  }
});

$('#schedule-submit').on('click', function () {
  var inputs = $("#schedule-form").find('input, [name], [data-name]');
  // inputs.each(function (index, item) {
  //   var val = $(item).val();
  //   if (!val && val !== 0 && val !== false) {
  //     $(item).attr('data-name', $(item).attr('name'));
  //     $(item).removeAttr('name');
  //   } else if (!$(item).attr('name')) {
  //     $(item).attr('name', $(item).attr('data-name'));
  //   }
  // });
  var spec = $("#schedule_spec").val();
  $("#schedule_spec").val(spec.trim().split(" ").join("|"));
  // showLoading();
  $('#schedule-form').submit();
  return false;
});


$(function () {
  $('.cdt-select').on('click', '.cdt-info .del', function() {
    $(this).parents('.cdt-select').siblings('[value="'+ $(this).parent().data('id') +'"]').removeAttr('value');
  });
  $('.cdt-select').each(function () {
    var $this = $(this);
    var datas = $this.data("json");
    var hots = [];
    var key = $this.data('key');
    if (key && key !== 'name') {
      for (var i in datas) {
        datas[i].name = datas[i][key];
      }
    }
    for (var i in datas) {
      hots.push(datas[i].name);
    }
    var selector = $this.cdtSelect({
      dataJson: datas,
      multiSelect: $(this).data("multi") || false,
      search: true,
      hotcdt: hots,
      onCallerAfter: function (target, values) {
        var vals = $this.find(".cdt-info span").map(function (i, v) {
          return $(v).data('id')
        });
        var $inputs = $this.siblings("input");
        vals.each(function (i, v) {
          if ($inputs[i])
            $($inputs[i]).val(v);
          else {
            var $input = $($inputs[0]).clone();
            $input.attr('type', 'hidden');
            $input.val(v);
            $this.before($input);
          }
        })
        $inputs.each(function (i, v) {
          if (i >= vals.length)
            $(v).remove();
          }
        )
      },
      onAjaxSearch: function (value, target) {
        var result = [];
        var keywords = $(target).parents('.cdt-select').data('keywords');
        if (!keywords)
          keywords = 'name';
        keys = keywords.split('|');
        cdts = keys.map(function (k) {
          return k + '=' + value;
        }).join('&');
        $.ajax({
          url: $this.data("search-url") + "?" + cdts,
          type: "GET",
          async: false,
          success: function (data) {
            result = data.list || data;
          },
          error: function (err) {}
        });
        if (key) {
          for (var i in result) {
            result[i].name = result[i][key];
          }
        }
        return result;
      }
    });
    (($this.data("default") || "") + "").split(",").forEach(function(v) {
      console.log(v)
       selector.setcdtVal(v.toString());
    })

    if ($this.hasClass('force-default')) { // FIX selector bug，当选项出现,分隔符时无法设置默认选中
      selector.$selector.find('.cdt-input')
                        .siblings('span').remove()
                        .end()
                        .before('<span data-id="'+ $this.data("default") +'">'+ $this.data("default") +'<i class="del"></i></span>');
    }
  })

  $('.cdt-select[disabled] input').attr('disabled', true).attr('placeholder', '不可修改');

  $('.cdt-select[disabled] input').on('input', function(e) {
    e.preventDefault();
    return false;
  })
  $('.cdt-select[disabled] *').on('click', function(e) {
    e.preventDefault();
    return false;
  })
})
</script>

app/views/schedules/_list.html.erb
<table class="table table-striped table-hover table-bscheduleed" id="editable-sample">
  <thead>
    <tr>
      <th>计划编号</th>
      <th>计划名称</th>
      <th>执行者</th>
      <th>预计执行时间</th>
      <th>截止时间</th>
      <th>状态</th>
      <th>关联车头</th>
      <th>关联挂车</th>
      <th>计划描述</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <!-- 此处动态生成 -->
    <% @schedules.each do |o| %>
      <tr>
        <td><%= link_to o.id, schedule_path(o) %></td>
        <td><%= link_to o.name, schedule_path(o) %></td>
        <td><%= o.executor %></td>
        <td><%= o.begin_time.try :strftime, '%Y-%m-%d %H:%M:%S' %></td>
        <td><%= o.end_time.try :strftime, '%Y-%m-%d %H:%M:%S' %></td>
        <td><%= o.state %></td>
        <td><%= link_to (o.car_head.try :car_number) || '', car_head_path(o.car_head_id.blank? ? 0 : o.car_head_id) %></td>
        <td><%= link_to (o.car_body.try :body_id) || '', car_body_path(o.car_body_id.blank? ? 0 : o.car_body_id) %></td>
        <td><%= o.desc.slice(0, 30) %></td>
        <td>
          <%= link_to '查看', schedule_path(o) %>
          |
          <%= link_to '编辑', edit_schedule_path(o) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/schedules/edit.html.erb
<!-- page heading start-->
<div class="page-heading">
  <h3>
    修改计划
  </h3>
  <ul class="breadcrumb">
    <li>
      <%= link_to '计划详情', schedule_path(@schedule) %>
    </li>
    <li class="active">
      编辑
    </li>
  </ul>
</div>
<!-- page heading end-->

<%= render 'form', schedule: @schedule %>

<script>
</script>

app/views/schedules/index.html.erb
<!-- page heading start-->
<div class="page-heading">
  <ul class="breadcrumb">
    <li>
      <a href="">计划管理</a>
    </li>
    <li class="active">
      <a href="/schedules">计划列表</a>
    </li>
    <li class="pull-right flex">
      <form class="" id='proSearch' method="get">
        <input type="text" class="form-control" name="keywords" placeholder="输入关键词搜索计划"/>
      </form>
    </li>
  </ul>
</div>
<!-- page heading end-->

<!--body wrapper start-->
<div class="wrapper">
  <div class="row">
    <div class="col-sm-12">
      <% if notice %>
        <h4 style="color: #ff6666"><%= notice %></h4>
      <% end %>
      <section class="panel">
        <div class="panel-heading">
          <div class="clearfix">
            <div class="btn-group">
                <a href="/schedules/new" id="editable-sample_new" class="btn btn-primary">
                    创建计划 <i class="fa fa-plus"></i>
                </a>
            </div>
            <div class="btn-group pull-right">
              <button id='btn-show-block' class="btn btn-default active">
                <i class="fa fa-th-large"></i>
              </button>
              <button id='btn-show-table' class="btn btn-default">
                <i class="fa fa-bars"></i>
              </button>
              <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">工具
                <i class="fa fa-angle-down"></i>
              </button>
              <ul class="dropdown-menu pull-right">
                <li>
                  <a href="javascript:void(0)" id="print">打印</a>
                </li>
                <li>
                  <a href="javascript:void(0)" id="export">导出为Excel</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <div class="adv-table editable-table ">
            <%= render "cdts" unless params[:pjax] == 'true' %>
            <!-- <div class="space15"></div> -->
            <% if params[:keywords] %>
              <div style="padding-left: 15px; padding-top: 15px;">
                搜索"<%= params[:keywords] %>"：
              </div>
            <% end %>
            <div id="pjax-replace">
              <% cache @schedules.cache_key, expires_in: 2.minutes do %>
                <!--startprint-->
                <div class="show-table">
                  <%= render "list" %>
                </div>
                <!--endprint-->
                <input type="hidden" id="total_count" value="<%= @schedules.total_count %>">
                <%= paginate @schedules %>
              <% end %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>
<!--body wrapper end-->

<script type="text/javascript">
  var $t = null;
  $('body').on('click', '.new-shipping-record', function() {
    $('#shipping-model').modal();
    $("#shipping-form").attr('action', $(this).data('href'))
    $t = $(this);
  })
  $("#confirm-shipping").on('click', function() {
    // $("#shipping-form").submit();
    var $form = $("#shipping-form");
    var data = new FormData($form[0]);
    console.log(location.origin + $form.attr('action'))
    $.ajax({
      url: location.origin + $form.attr('action'),
      data: data,
      type: 'POST',
      dataType: 'JSON',
      processData: false,
      success: function() {
        if ($t) {
          $t.siblings('span.split').remove();
          $t.remove();
        }
      },
      error: function() {
        alert('啊啊啊，出错啦！！！快去找可爱的达达来解决！');
      },
      complete: function() {
        $('#shipping-model').modal('hide');
      }
    });
    return false;
  })
</script>
<%= stylesheet_link_tag 'share/selector' %>
<%= javascript_include_tag 'share/selector' %>
<script type="text/javascript">
  $("#export").on('click', function() {
    if ($('.cdts-panel #cdts').css('display') === 'none') {
      alert('请先筛选条件选择导出计划');
      $('.cdts-panel [role="show-cdts"]').click();
      return;
    }
    var total_count = $("#total_count").val();
    var bool =confirm('根据当前条件筛选，即将导出' + total_count + '条数据，是否继续？');
    if (bool) {
      var search = decodeURI(location.search);
      const cons = [];
      search.replace('?&', '?').slice(1).split('&').forEach(function(v) {
        var c = v.split('=');
        cons.push([c[0], c[1]]);
      })
      showLoading('正在导出中...');
      var form = $("<form></form>");
      form.hide();
      form.attr('action', '/schedules/export/xlsx');
      form.attr('method', 'get');
      cons.forEach(function(v) {
        form.append('<input type=hidden name="' + v[0] + '" value="'+ v[1] +'">')
      })
      $('body').after(form);
      form.submit();
      form.remove();
      setTimeout(hideLoading, 1500);
    }
  })
</script>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<!-- page heading start-->
<div class="page-heading">
  <ul class="breadcrumb">
    <li>
      <a href="/schedules">计划管理</a>
    </li>
    <li class="active">
      <a href="">计划：<%= @schedule.name %></a>
    </li>
    <li class="pull-right flex">
    </li>
  </ul>
</div>
<!-- page heading end-->

<div class="wrapper @schedule-detail">
  <div class="row">
    <div class="col-md-12">
      <% if notice %>
        <h4 style="color: #ff6666"><%= notice %></h4>
      <% end %>
      <div class="panel">
        <div class="panel-heading">
          计划详情
          <small>
            <%= link_to '编辑', edit_schedule_path(@schedule), class: 'pull-right flex' %>
          </small>
        </div>
        <div class="panel-body">

          <ul class="p-info o-info">
            <li>
              <div class="title">计划名</div>
              <div class="desk"><%= @schedule.name %></div>
            </li>
            <li>
              <div class="title">执行者</div>
              <div class="desk"><%= @schedule.executor %></div>
            </li>
            <li>
              <td>
                <div class="title">预计执行时间 </div>
                <div class="desk"><%= @schedule.begin_time.try :strftime, '%Y-%m-%d %H:%M:%S' %></div>
              </td>
            </li>
            <li>
              <td>
                <div class="title">截止时间 </div>
                <div class="desk"><%= @schedule.end_time.try :strftime, '%Y-%m-%d %H:%M:%S' %></div>
              </td>
            </li>
            <li>
              <div class="title">车牌号</div>
              <div class="desk">
                <td><%= link_to (@schedule.car_head.try :car_number) || '', car_head_path(@schedule.car_head_id.blank? ? 0 : @schedule.car_head_id) %></td>
              </div>
            </li>
            <li>
              <div class="title">挂车号</div>
              <div class="desk">
                <td><%= link_to (@schedule.car_body.try :body_id) || '', car_body_path(@schedule.car_body_id.blank? ? 0 : @schedule.car_body_id) %></td>
              </div>
            </li>
            <li>
              <div class="title">计划状态</div>
              <div class="desk"><%= @schedule.state %></div>
            </li>
            <li>
              <div class="title">计划描述</div>
              <div class="desk"><%= @schedule.desc %></div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <%= link_to '返回', schedules_path %>
  <%= link_to '删除计划', schedule_path(@schedule), method: :delete, data: { confirm: "确定删除该计划吗？" }, class: 'pull-right flex' %>
</div>