config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :sales
  resources :drivers
  resources :car_bodies
  resources :car_heads
  resources :orders
  resources :admins

  get '' => 'main#index', as: :root

  # session
  get 'login' => 'session#index', as: :login
  post 'login' => 'session#login', as: :do_login
  post 'logout' => 'session#logout', as: :logout

  get 'profile' => 'admins#profile', as: :profile

  # counts
  get 'counts' => 'main#counts'
  get 'products_count' => 'main#products_count'
  get 'viewers_count' => 'main#viewers_count'
  get 'total_count' => 'main#total_count'
  get 'statistic_order_map' => 'main#statistic_order_map'
  post 'upload_token' => 'image_uploader#get_upload_token'
  post 'upload_video_token' => 'image_uploader#upload_video_token'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :gen_number_series
  before_update do # 记录上一个状态
    self.last_state = self.state_was if self.will_save_change_to_state?
  end

  validates :price, numericality: { greater_than_or_equal_to: 0 }
  # validates :remark, length: { maximum: 1024, too_long: '订单备注最大长度为%{count}' }
  # validates :pay_type, inclusion: { in: %w[ali wx] }, allow_blank: true
  validates :state, presence: true, allow_blank: false

  scope :with_del, -> { unscope(where: :is_deleted) }
  scope :deleted, -> { where(is_deleted: true) }
  scope :undeleted, -> { where(is_deleted: false) }
  scope :success, -> { unscope(where: :state).where(state: [1, 2, 3, 4, 5]) }
  scope :timeout, -> { unscope(where: :state).onpaying.where('created_at < ?', Time.now - 7.days) }
  scope :onprogress, -> { unscope(where: :state).where(state: %i[onpaying1 onloading ondelivering onpaying2]) }
  default_scope { order(created_at: :desc) }

  # 0=>待付首款, 1=>装车中, 2=>运输中, 3=>已送达, 4=>待付尾款, 5=>已完成, 6=>订单取消, 7=>已退款
  enum state: { onpaying1: 0, onloading: 1, ondelivering: 2, arrived: 3, onpaying2: 4, completed: 5, canceled: 6, refunded: 7 }

  has_and_belongs_to_many :drivers
  has_and_belongs_to_many :sales

  belongs_to :car_head,
             foreign_key: :car_number,
             optional: true

  belongs_to :car_body,
             optional: true

  def self.new(attrs = {}, &blk)
    order = super &blk
    order.attributes = attrs
    order.state ||= :completed
    order
  end

  def self.create!(*args, &blk)
    order = new
    order.create! *args, &blk
  end

  def create!(attrs)
    order = self
    order.attributes = attrs
    order.save!
    order
  end

  # 所有订单禁止真删除
  def delete
    delete!
  rescue StandardError
    false
  end

  def delete!
    is_deleted = true
    save!
  end

  def self.destroy
    delete!
  rescue StandardError
    false
  end

  def self.destroyed!
    delete!
  end

  def self.filter(cons = {})
    _self = self
    _self = _self.where(id: (Driver.find_by_id(cons[:driver_id]) || Driver.none).orders) if cons[:driver_id]
    _self = _self.where(id: (Sale.find_by_id(cons[:sale_id]) || Sale.none).orders) if cons[:sale_id]
    if cons[:keywords]
      k = cons[:keywords]
      _self = _self.where('order_number like ?
                           OR origin LIKE ?
                           OR destination LIKE ?
                           OR customer_name LIKE ?
                           OR customer_tel LIKE ?',
                           "%#{k}%", "%#{k}%", "%#{k}%", "%#{k}%", "%#{k}%")
    end
    _self = _self.unscope(where: :states).where(state: cons[:states]) if cons[:states] # 数组
    _self = _self.success if cons[:state_] == "success"
    _self = _self.onprogress if cons[:state_] == "onprogress"
    _self = _self.unscope(where: :states).where(state: cons[:states]) if cons[:states] # 数组

    _self = _self.where('origin LIKE ?', "%#{cons[:origin]}%") if cons[:origin]
    _self = _self.where('destination LIKE ?', "%#{cons[:destination]}%") if cons[:destination]
    _self = _self.where('orders.start_time <= ?', cons[:fache_before]) if cons[:fache_before]
    _self = _self.where('orders.start_time >= ?', cons[:fache_after]) if cons[:fache_after]
    _self = _self.where('price <= ?', cons[:price_ceil]) if cons[:price_ceil]
    _self = _self.where('price >= ?', cons[:price_floor]) if cons[:price_floor]
    _self
  end

  def payed?
    !onpaying? && !canceled?
  end

  def self.STATE_TEXT
    {
      onpaying1: '待付首款',
      onloading: '装车中',
      ondelivering: '运输中',
      arrived: '已送达',
      onpaying2: '待付尾款',
      completed: '已完成',
      canceled: '已取消',
      refunded: '已退款'
    }
  end

  def state_text
    self.class.STATE_TEXT[state.to_sym] || state
  end

  def close! # 关闭订单
    # return refund! if can_refund?
    cancel!
  end

  def pay_type_text
    # return '支付宝' if self.pay_type == 'ali'
    # return '微信' if self.pay_type == 'wx'
    self.pay_type
  end

  def drivers_name
    (drivers.map {|d| d.name}).join(', ')
  end

  def sales_name
    (sales.map {|s| s.name}).join(', ')
  end

  def self.statistics_map time_begin, time_end
    os = Order.where(start_time: time_begin..time_end).all
    map = {}
    os.each do |o|
      if !o.origin.blank? && !o.destination.blank? then
         ori = o.origin.end_with?('市') ? o.origin.chop : o.origin
         map[ori] ||= []
         map[ori] << (o.destination.end_with?('市') ? o.destination.chop : o.destination)
       end
    end
    map
  end

  private

  def gen_number_series
    now = Time.now
    series = now.year.to_s + now.month.to_s + now.day.to_s
    series += rand.to_s.gsub!('0.', '')
    self.order_number = series
    series
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :filter_cons, only: [:index, :onprogress, :completed, :onrefunding, :refunded, :export_xlsx]
  before_action :set_order, only: [:show, :edit, :update, :delivery, :refund, :cancel]


  # GET /orders
  # GET /orders.json
  def index
	  nonpaged_orders = Order.filter(@cons).includes(:drivers, :sales, :car_head, :car_body)
    @orders = nonpaged_orders.page(@page).per(@count)
	end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: '订单已创建.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: '订单已更新.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: '订单已删除.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:price, :driver_id, {driver_ids: []}, {sale_ids: []}, :car_number, :car_body_id, :customer_name, :customer_tel, :goods, :weight, :origin, :destination, :distance, :start_time, :end_time, :oil_consumption, :oil_fee, :toll_gate, :road_toll, :state, :customer_id, :sale_name, :total_fee, :pay1_type, :pay1_time, :pay1_amount, :pay2_type, :pay2_time, :pay2_amount, :via_stations, :remark)
    end

    def filter_cons
  		@count = params[:count] || 20
  		@page = params[:page] || 1
  		@cons = params.slice(:keywords, :states, :state_, :number, :driver_id, :sale_id, :fache_before, :fache_after, :price_ceil, :price_floor, :origin, :destination)
	  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_cdts.html.erb
<div class="cdts-panel">
	<header class="panel-heading c">
		<small>条件筛选</small>
		<span class="tools pull-right">
			<a class="fa fa-chevron-down" href="javascript:;" role='show-cdts'></a>
		 </span>
	</header>

	<ul class='cdts' id="cdts" style="display: none">
		<% if params[:action].to_sym == :index %>
			<li>
				<div class="options"  data-multi='true'>
					<ul class="directory-list">
						<li class='con-item' id='state' data-name="states[]">状态</li>
						<% Order.states.keys.each do |k| %>
							<li><a href="JavaScript: void(0)" data-value="<%= k %>" data-role='opt'><%= Order.STATE_TEXT[k.to_sym] %></a></li>
						<% end %>
						<li><a href="JavaScript: void(0)" data-role='opt'>不限</a></li>
					</ul>
				</div>
			</li>
		<% end %>
		<li class="inline">
				<div class="options" data-multi='true'>
				<ul class="directory-list">
					<li class='con-item' id='create_begin' data-name="fache_after">发车日期</li>
					<span class="opt-tip">开始</span>
					<li>
						<a href="JavaScript: void(0)" data-value data-role='opt'>
							<input type="text" class="date input" autocomplete="off">
						</a>
					</li>
				</ul>
			</div>
		</li>
		<li class="inline">
			<div class="options" data-multi='true'>
				<ul class="directory-list">
					<li class='con-item' id='create_end' data-name="fache_before"></li>
					<span class="opt-tip">截止</span>
					<li>
						<a href="JavaScript: void(0)" data-value data-role='opt'>
							<input type="text" class="date input" role='order-end-time' autocomplete="off">
						</a>
					</li>
				</ul>
			</div>
		</li>
		<br>
		<li class="inline">
				<div class="options" data-multi='true'>
				<ul class="directory-list">
					<li class='con-item' id='origin' data-name="origin">发车地</li>
					<li>
						<a href="JavaScript: void(0)" data-value data-role='opt'>
							<input type="text" class="" autocomplete="off">
						</a>
					</li>
				</ul>
			</div>
		</li>
		<li class="inline">
			<div class="options" data-multi='true'>
				<ul class="directory-list">
					<li class='con-item' id='shipping_end' data-name="destination"></li>
					<span class="opt-tip">目的地</span>
					<li>
						<a href="JavaScript: void(0)" data-value data-role='opt'>
							<input type="text" class="" autocomplete="off">
						</a>
					</li>
				</ul>
			</div>
		</li>
		<br>
		<li class="inline">
			<div class="options" data-multi='true'>
				<ul class="directory-list">
					<span></span>
					<li class='con-item' id='price_floor' data-name="price_floor">价格区间</li>
					<span class="opt-tip">大于等于</span>
					<li>
						<a href="JavaScript: void(0)" data-value data-role='opt'>
							<input type="text" class="input" placeholder="请输入数字, 回车搜索">
						</a>
					</li>
				</ul>
			</div>
		</li>
		<li class="inline">
			<div class="options" data-multi='true'>
				<ul class="directory-list">
					<li class='con-item' id='price_ceil' data-name="price_ceil"></li>
					<span class="opt-tip">小于等于</span>
					<li>
						<a href="JavaScript: void(0)" data-value data-role='opt'>
							<input type="text" class="input" placeholder="请输入数字, 回车搜索">
						</a>
					</li>
				</ul>
			</div>
		</li>
	</ul>
</div>

<%= stylesheet_link_tag "cdtSelector/cdt-select" %>
<%= javascript_include_tag "cdtSelector/cdtSelect" %>
<script type="text/javascript">
	// 处理特殊的截止时间 时间+1天
	$('[role="order-end-time"]').on('change', function() {
		if ($(this).val()) {
			var d = new Date($(this).val());
			d.setDate(d.getDate() + 1)
			$(this).val([d.getFullYear(), d.getMonth() + 1, d.getDate()].join('-'));
		}
	})
</script>

app/views/orders/_list.html.erb
<table class="table table-striped table-hover table-bordered" id="editable-sample">
  <thead>
    <tr>
      <th>订单编号</th>
      <th>客户姓名</th>
      <th>客户手机</th>
      <th>订单价格</th>
      <th>司机姓名</th>
      <th>车头(车牌号)</th>
      <th>挂车号</th>
      <th>货物</th>
      <th>重量</th>
      <th>发货地</th>
      <th>目的地</th>
      <th>发车时间</th>
      <th>业务员</th>
      <th>订单状态</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <!-- 此处动态生成 -->
    <% @orders.each do |o| %>
      <tr>
        <td><%= link_to o.id, order_path(o) %></td>
        <td><%= o.customer_name %></td>
        <td><%= o.customer_tel %></td>
        <td>
          <span>
            <i class='fa fa-rmb'></i><%= o.price %>
          </span>
        </td>
        <td>
          <% o.drivers.each do |d| %>
            <%= link_to d.name + ' ', driver_path(d) %>
          <% end %>
        </td>
        <td><%= link_to (o.car_head.try :car_number) || '', car_head_path(o.car_number.blank? ? 0 : o.car_number) %></td>
        <td><%= link_to (o.car_body.try :body_id) || '', car_body_path(o.car_body_id.blank? ? 0 : o.car_body_id) %></td>
        <td><%= o.goods %></td>
        <td><%= o.weight %></td>
        <td><%= o.origin %></td>
        <td><%= o.destination %></td>
        <td><%= o.start_time.try :strftime, '%Y-%m-%d %H:%M:%S' %></td>
        <td>
          <% o.sales.each do |s| %>
            <%= link_to s.name + ' ', sale_path(s) %>
          <% end %>
        </td>
        <td><%= o.state_text %></td>
        <td>
          <%= link_to '查看', order_path(o) %>
          |
          <%= link_to '编辑', edit_order_path(o) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/edit.html.erb
<!-- page heading start-->
<div class="page-heading">
  <h3>
    修改订单
  </h3>
  <ul class="breadcrumb">
    <li>
      <%= link_to '订单详情', order_path(@order) %>
    </li>
    <li class="active">
      编辑
    </li>
  </ul>
</div>
<!-- page heading end-->

<%= render 'form', order: @order %>

<script>
</script>

app/views/orders/index.html.erb
<!-- page heading start-->
<div class="page-heading">
  <ul class="breadcrumb">
    <li>
      <a href="">订单管理</a>
    </li>
    <li class="active">
      <a href="/orders">订单列表</a>
    </li>
    <li class="pull-right flex">
      <form class="" id='proSearch' method="get">
        <input type="text" class="form-control" name="keywords" placeholder="输入关键词搜索订单"/>
      </form>
    </li>
  </ul>
</div>
<!-- page heading end-->

<!--body wrapper start-->
<div class="wrapper">
  <div class="row">
    <div class="col-sm-12">
      <% if notice %>
        <h4 style="color: #ff6666"><%= notice %></h4>
      <% end %>
      <section class="panel">
        <div class="panel-heading">
          <div class="clearfix">
            <div class="btn-group">
                <a href="/orders/new" id="editable-sample_new" class="btn btn-primary">
                    创建订单 <i class="fa fa-plus"></i>
                </a>
            </div>
            <div class="btn-group pull-right">
              <button id='btn-show-block' class="btn btn-default active">
                <i class="fa fa-th-large"></i>
              </button>
              <button id='btn-show-table' class="btn btn-default">
                <i class="fa fa-bars"></i>
              </button>
              <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">工具
                <i class="fa fa-angle-down"></i>
              </button>
              <ul class="dropdown-menu pull-right">
                <li>
                  <a href="javascript:void(0)" id="print">打印</a>
                </li>
                <li>
                  <a href="javascript:void(0)" id="export">导出为Excel</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <div class="adv-table editable-table ">
            <!-- <div class="space15"></div> -->
            <%= render "cdts" unless params[:pjax] == 'true' %>
            <% if params[:keywords] %>
              <div style="padding-left: 15px; padding-top: 15px;">
                搜索"<%= params[:keywords] %>"：
              </div>
            <% end %>
            <div id="pjax-replace">
              <% cache @orders.cache_key, expires_in: 2.minutes do %>
                <!--startprint-->
                <div class="show-table">
                  <%= render "list" %>
                </div>
                <!--endprint-->
                <input type="hidden" id="total_count" value="<%= @orders.total_count %>">
                <%= paginate @orders %>
              <% end %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>
<!--body wrapper end-->

<script type="text/javascript">
  var $t = null;
  $('body').on('click', '.new-shipping-record', function() {
    $('#shipping-model').modal();
    $("#shipping-form").attr('action', $(this).data('href'))
    $t = $(this);
  })
  $("#confirm-shipping").on('click', function() {
    // $("#shipping-form").submit();
    var $form = $("#shipping-form");
    var data = new FormData($form[0]);
    console.log(location.origin + $form.attr('action'))
    $.ajax({
      url: location.origin + $form.attr('action'),
      data: data,
      type: 'POST',
      dataType: 'JSON',
      processData: false,
      success: function() {
        if ($t) {
          $t.siblings('span.split').remove();
          $t.remove();
        }
      },
      error: function() {
        alert('啊啊啊，出错啦！！！快去找可爱的达达来解决！');
      },
      complete: function() {
        $('#shipping-model').modal('hide');
      }
    });
    return false;
  })
</script>
<%= stylesheet_link_tag 'share/selector' %>
<%= javascript_include_tag 'share/selector' %>
<script type="text/javascript">
  $("#export").on('click', function() {
    if ($('.cdts-panel #cdts').css('display') === 'none') {
      alert('请先筛选条件选择导出订单');
      $('.cdts-panel [role="show-cdts"]').click();
      return;
    }
    var total_count = $("#total_count").val();
    var bool =confirm('根据当前条件筛选，即将导出' + total_count + '条数据，是否继续？');
    if (bool) {
      var search = decodeURI(location.search);
      const cons = [];
      search.replace('?&', '?').slice(1).split('&').forEach(function(v) {
        var c = v.split('=');
        cons.push([c[0], c[1]]);
      })
      showLoading('正在导出中...');
      var form = $("<form></form>");
      form.hide();
      form.attr('action', '/orders/export/xlsx');
      form.attr('method', 'get');
      cons.forEach(function(v) {
        form.append('<input type=hidden name="' + v[0] + '" value="'+ v[1] +'">')
      })
      $('body').after(form);
      form.submit();
      form.remove();
      setTimeout(hideLoading, 1500);
    }
  })
</script>

app/views/orders/new.html.erb
<!-- page heading start-->
<div class="page-heading">
    <h3>
        新建订单
    </h3>
    <ul class="breadcrumb">
        <li>
            <%= link_to '全部订单', orders_path %>
        </li>
        <li class="active"> 新建 </li>
    </ul>
    <% if notice %>
      <h4 class="form-error"><%= notice %></h4>
    <% end %>
</div>
<!-- page heading end-->
<%= render 'form', order: @order %>

<script>

</script>

app/views/orders/show.html.erb
<!-- page heading start-->
<div class="page-heading">
  <ul class="breadcrumb">
    <li>
      <a href="/orders">订单管理</a>
    </li>
    <li class="active">
      <a href="">订单<%= @order.order_number %></a>
    </li>
    <li class="pull-right flex">
    </li>
  </ul>
</div>
<!-- page heading end-->

<div class="wrapper @order-detail">
  <div class="row">
    <div class="col-md-12">
      <% if notice %>
        <h4 style="color: #ff6666"><%= notice %></h4>
      <% end %>
      <div class="panel">
        <div class="panel-heading">
          订单详情
          <small>
            <%= link_to '编辑', edit_order_path(@order), class: 'pull-right flex' %>
          </small>
        </div>
        <div class="panel-body">

          <ul class="p-info o-info">
            <li>
              <div class="title">订单编号</div>
              <div class="desk"><%= @order.id %></div>
            </li>
            <li>
              <div class="title">订单价格</div>
              <div class="desk"><%= @order.price %>元</div>
            </li>
            <li>
              <div class="title">客户姓名</div>
              <div class="desk"><%= @order.customer_name %></div>
            </li>
            <li>
              <div class="title">客户手机号</div>
              <div class="desk"><%= @order.customer_tel %></div>
            </li>
            <li>
              <div class="title">司机</div>
              <div class="desk">
                <% @order.drivers.each do |d| %>
                  <%= link_to d.name + ' ', driver_path(d) %>
                <% end %>
              </div>
            </li>
            <li>
              <div class="title">业务员</div>
              <div class="desk">
                <% @order.sales.each do |s| %>
                  <%= link_to s.name + ' ', sale_path(s) %>
                <% end %>
              </div>
            </li>
            <li>
              <div class="title">车牌号</div>
              <div class="desk">
                <td><%= link_to (@order.car_head.try :car_number) || '', car_head_path(@order.car_number.blank? ? 0 : @order.car_number) %></td>
              </div>
            </li>
            <li>
              <div class="title">挂车号</div>
              <div class="desk">
                <td><%= link_to (@order.car_body.try :body_id) || '', car_body_path(@order.car_body_id.blank? ? 0 : @order.car_body_id) %></td>
              </div>
            </li>
            <li>
              <div class="title">货物</div>
              <div class="desk"><%= @order.goods %></div>
            </li>
            <li>
              <div class="title">货重</div>
              <div class="desk"><%= @order.weight %></div>
            </li>
            <li>
              <div class="title">发车地</div>
              <div class="desk"><%= @order.origin %></div>
            </li>
            <li>
              <div class="title">目的地</div>
              <div class="desk"><%= @order.destination %></div>
            </li>
            <li>
              <div class="title">途经站点</div>
              <div class="desk"><%= @order.via_stations %></div>
            </li>
            <li>
              <div class="title">运输距离</div>
              <div class="desk"><%= @order.distance %></div>
            </li>
            <li>
              <div class="title">发车时间</div>
              <div class="desk"><%= @order.start_time.try :strftime, '%Y-%m-%d %H:%M:%S' %></div>
            </li>
            <li>
              <div class="title">送到时间</div>
              <div class="desk"><%= @order.end_time.try :strftime, '%Y-%m-%d %H:%M:%S' %></div>
            </li>
            <li>
              <div class="title">油耗</div>
              <div class="desk"><%= @order.oil_consumption || 0 %>升</div>
            </li>
            <li>
              <div class="title">油费</div>
              <div class="desk"><%= @order.toll_gate || 0 %>元</div>
            </li>
            <li>
              <div class="title">过路费</div>
              <div class="desk"><%= @order.road_toll || 0 %>元</div>
            </li>
            <li>
              <div class="title">订单总成本</div>
              <div class="desk"><%= @order.total_fee || 0 %>元</div>
            </li>
            <li>
              <div class="title">预计收益</div>
              <div class="desk"><%= (@order.price || 0) - (@order.total_fee || 0) %>元</div>
            </li>
            <li>
              <div class="title">订单状态</div>
              <div class="desk"><%= @order.state_text %></div>
            </li>
            <li>
              <div class="title">销售员</div>
              <div class="desk"><%= (@order.sales.map {|s| s.name}).join(", ") %></div>
            </li>
            <li>
              <div class="title">首款支付方式</div>
              <div class="desk"><%= @order.pay1_type %></div>
            </li>
            <li>
              <div class="title">首款支付时间</div>
              <div class="desk"><%= @order.pay1_time.try :strftime, '%Y-%m-%d %H:%M:%S' %></div>
            </li>
            <li>
              <div class="title">首款支付金额（元）</div>
              <div class="desk"><%= @order.pay1_amount %></div>
            </li>
            <li>
              <div class="title">尾款支付方式</div>
              <div class="desk"><%= @order.pay2_type %></div>
            </li>
            <li>
              <div class="title">尾款支付时间</div>
              <div class="desk"><%= @order.pay2_time.try :strftime, '%Y-%m-%d %H:%M:%S' %></div>
            </li>
            <li>
              <div class="title">尾款支付金额（元）</div>
              <div class="desk"><%= @order.pay2_amount %></div>
            </li>
            <li>
              <div class="title">订单备注</div>
              <div class="desk"><%= @order.remark %></div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <%= link_to '返回', orders_path %>
  <%= link_to '删除订单', order_path(@order), method: :delete, data: { confirm: "确定删除该订单吗？" }, class: 'pull-right flex' %>
</div>