config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :sales
  resources :drivers
  resources :car_bodies
  resources :car_heads
  resources :orders
  resources :admins

  get '' => 'main#index', as: :root

  # session
  get 'login' => 'session#index', as: :login
  post 'login' => 'session#login', as: :do_login
  post 'logout' => 'session#logout', as: :logout

  get 'profile' => 'admins#profile', as: :profile

  # counts
  get 'counts' => 'main#counts'
  get 'products_count' => 'main#products_count'
  get 'viewers_count' => 'main#viewers_count'
  get 'total_count' => 'main#total_count'
  get 'statistic_order_map' => 'main#statistic_order_map'
  post 'upload_token' => 'image_uploader#get_upload_token'
  post 'upload_video_token' => 'image_uploader#upload_video_token'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
  has_and_belongs_to_many :orders

  def orders_count
    self.orders.success.count
  end

  def orders_money
    self.orders.success.sum(:price)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @count = params[:count] || 20
    @page = params[:page] || 1
    nonpaged_orders =  @sale.orders.includes(:drivers, :sales, :car_head, :car_body)
    @orders = nonpaged_orders.page(@page).per(@count)
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:name, :tel, :gender, :age, :join_time, :info, :remark)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :sale_name %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel, id: :sale_tel %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.number_field :gender, id: :sale_gender %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :sale_age %>
  </div>

  <div class="field">
    <%= form.label :join_time %>
    <%= form.text_field :join_time, id: :sale_join_time %>
  </div>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_field :info, id: :sale_info %>
  </div>

  <div class="field">
    <%= form.label :remark %>
    <%= form.text_field :remark, id: :sale_remark %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<!-- page heading start-->
<div class="page-heading">
    <h3>
        业务员管理
    </h3>
    <ul class="breadcrumb">
        <li>
            <a href="#">业务员列表</a>
        </li>
    </ul>
</div>
<!-- page heading end-->

<!--body wrapper start-->
<div class="wrapper">
     <div class="row">
        <div class="col-sm-12">
            <section class="panel">
                <!-- <header class="panel-heading">
                    Editable Table
                    <span class="tools pull-right">
                        <a href="javascript:;" class="fa fa-chevron-up toggle-show"></a>
                        <a href="javascript:;" class="fa fa-times"></a>
                     </span>
                </header> -->
                <div class="panel-body">
                    <div class="adv-table editable-table ">
                        <div class="clearfix">
                            <div class="btn-group">
                                <button id="editable-sample_new" class="btn btn-primary">
                                    添加业务员 <i class="fa fa-plus"></i>
                                </button>
                            </div>
                            <!-- <div class="btn-group pull-right">
                                <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">工具 <i class="fa fa-angle-down"></i>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="#">打印</a></li>
                                    <li><a href="#">导出Excel</a></li>
                                </ul>
                            </div> -->
                        </div>
                        <br>
                        <div class="space15"></div>
                        <table class="table table-striped table-hover table-bordered" id="editable-sample">
                        <thead>
                            <tr>
                                <th>姓名</th>
                                <th>电话</th>
                                <th>性别</th>
                                <th>出生日期</th>
                                <th>入职时间</th>
                                <th>运单总数</th>
                                <th>编辑</th>
                                <th>删除</th>
                            </tr>
                        </thead>
                            <tbody>
                                <% @sales.each do |sale| %>
                                    <tr class="">
                                        <td><%= link_to sale.name, sale %></td>
                                        <td><%= sale.tel %></td>
                                        <td><%= sale.gender %></td>
                                        <td><%= sale.age %></td>
                                        <td><%= sale.join_time %></td>
                                        <td><%= link_to sale.orders_count, orders_path(sale_id: sale.id)  %></td>
                                        <td><a class="edit" href="javascript:;" data-id='<%= sale.id %>'>编辑</a></td>
                                        <td><a class="delete" href="javascript:;" data-id='<%= sale.id %>'>删除</a></td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
<!--body wrapper end-->

<!-- END JAVASCRIPTS -->
<script>
    jQuery(document).ready(function() {
        EditableTable.init();
    });
</script>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<div class="page-heading">
  <ul class="breadcrumb">
    <li>
        <a href="/sales">业务员管理</a>
    </li>
    <li class="active">
      <a href="">详细信息</a>
    </li>
    <li class="pull-right flex">
    </li>
  </ul>
</div>

<div class="wrapper order-detail">
  <div class="row">
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-heading">
          业务员详情
        </div>
        <div class="panel-body">
          <ul class="p-info o-info">
            <li>
              <div class="title">姓名</div>
              <div class="desk"><%= @sale.name %></div>
            </li>
            <li>
              <div class="title">电话</div>
              <div class="desk"><%= @sale.tel %></div>
            </li>
            <li>
              <div class="title">性别</div>
              <div class="desk"><%= @sale.gender %></div>
            </li>
            <li>
              <div class="title">出生年月</div>
              <div class="desk"><%= @sale.age %></div>
            </li>
            <li>
              <div class="title">入职时间</div>
              <div class="desk"><%= @sale.join_time %></div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-heading">
          订单列表
        </div>
        <div class="panel-body">
          <%= render "/orders/list" %>
          <%= paginate @orders %>
        </div>
      </div>
    </div>
  </div>
</div>